name: CI
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: true

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Clean
        run: pnpm recursive run clean
        env:
          CI: true

      - name: Build
        run: pnpm recursive run build
        env:
          CI: true

      - name: Begin Tests
        run: pnpm recursive run test
        env:
          CI: true
